name: secp256k1-haskell
version: '0.1.2'
synopsis: Bindings for secp256k1 library from Bitcoin Core
description: Sign and verify signatures using the very fast C secp256k1 library from Pieter Wuille. Has Haskell types and abstractions for keys and signatures.
category: Crypto
author: Jean-Pierre Rupp
maintainer: xenog@protonmail.com
copyright: (c) 2017 Jean-Pierre Rupp
license: PublicDomain
license-file: UNLICENSE
github: haskoin/secp256k1-haskell.git
homepage: http://github.com/haskoin/secp256k1-haskell#readme
extra-source-files:
  - CHANGELOG.md
  - README.md
dependencies:
  - base >=4.8 && <5
  - base16-bytestring
  - bytestring
  - cereal
  - entropy
  - mtl
  - QuickCheck
  - string-conversions
library:
  source-dirs: src
  extra-libraries: secp256k1
tests:
  spec:
    defaults: hspec/hspec@master
    dependencies:
      - secp256k1-haskell
      - HUnit
